-- App schema

-- USER
CREATE TABLE "user" (
    id BIGINT CREATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    username varchar(128) NOT NULL UNIQUE
);


-- TASK
CREATE TABLE "task" (
    id BIGINT CREATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    username varchar(128) NOT NULL UNIQUE
);